# Generated by Django 5.1.3 on 2024-12-04 15:57

import reservas.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[reservas.validators.validar_telefono]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[reservas.validators.validar_username]),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='capacidad',
            field=models.IntegerField(validators=[reservas.validators.validar_capacidad_mesa]),
        ),
        migrations.AlterField(
            model_name='plato',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[reservas.validators.validar_precio_plato]),
        ),
    ]
